<?php

namespace Acme\BaseBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AttributeCollectionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AttributeCollectionRepository extends EntityRepository
{
}